package ucuenca.registrocapacitaciones;

import java.io.*;
import java.util.*;
import java.text.*;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class evento implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EVENTO_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "EVENTO_ID_GENERATOR", sequenceName = "EVENTO_ID_SEQ")
   private java.lang.Long id;

   private java.util.Date fecha;

   private java.lang.String nombre;

   private java.lang.String dependencia;

   private java.lang.String descripcion;

   @org.kie.api.definition.type.Label("Fecha de Inicio")
   private java.util.Date fechaInicio;

   @org.kie.api.definition.type.Label("Fecha de Finalización")
   private java.util.Date fechaFin;

   private java.lang.String horario;

   @org.kie.api.definition.type.Label("Duración en horas")
   private java.lang.Integer duracion;

   @org.kie.api.definition.type.Label("Centro de capacitación")
   private java.lang.String centro;

   @org.kie.api.definition.type.Label("País")
   private java.lang.String pais;

   private java.lang.String ciudad;

   private java.lang.String lugar;

   private java.lang.String modalidad;

   @org.kie.api.definition.type.Label("Instructor/es")
   private java.lang.String instructor;

   @org.kie.api.definition.type.Label("Financiado por")
   private java.lang.String financiamiento;

   private java.lang.Double costo;

   private java.lang.String justificacion;

   private java.lang.String observaciones;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Participantes")
   private java.util.List<ucuenca.registrocapacitaciones.participante> participantes;

   public evento()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getFecha()
   {
      return this.fecha;
   }

   public void setFecha(java.util.Date fecha)
   {
      this.fecha = fecha;
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getDependencia()
   {
      return this.dependencia;
   }

   public void setDependencia(java.lang.String dependencia)
   {
      this.dependencia = dependencia;
   }

   public java.lang.String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(java.lang.String descripcion)
   {
      this.descripcion = descripcion;
   }

   public java.util.Date getFechaInicio()
   {
     return this.fechaInicio;
   }

   public String getFechaInicioMod()
   {
        SimpleDateFormat formatter = new SimpleDateFormat("dd 'de' MMMM 'de' ");
        String fechaInicial = formatter.format(fechaInicio);
        return fechaInicial;
   }
   
   public String getYearInicio(){
       
        SimpleDateFormat formatter = new SimpleDateFormat("yy");
        String year = formatter.format(fechaInicio);
        return year;
   }

   public String getYearFin(){
       
        SimpleDateFormat formatter = new SimpleDateFormat("yy");
        String year = formatter.format(fechaFin);
        return year;
   }
   
   public void setFechaInicio(java.util.Date fechaInicio)
   {
      this.fechaInicio = fechaInicio;
   }

   public java.util.Date getFechaFin()
   {
        return this.fechaFin;
   }
   
   public String getFechaFinMod()
   {
        SimpleDateFormat formatter = new SimpleDateFormat("dd 'de' MMMM 'de' ");
        String fechaFinal = formatter.format(fechaFin);
        return fechaFinal;
   }


   public void setFechaFin(java.util.Date fechaFin)
   {
      this.fechaFin = fechaFin;
   }

 public String sumarDiasFecha(java.util.Date fecha, int dias){

      Calendar calendar = Calendar.getInstance();
      calendar.setTime(fecha); // Configuramos la fecha que se recibe
      calendar.add(Calendar.DAY_OF_YEAR, dias);  // numero de días a añadir, o restar en caso de días<0
      SimpleDateFormat formatter = new SimpleDateFormat("dd 'de' MMMM 'de' ");
      String fechaDL = formatter.format(calendar.getTime());
      return fechaDL;

 }

   public java.lang.String getHorario()
   {
      return this.horario;
   }

   public void setHorario(java.lang.String horario)
   {
      this.horario = horario;
   }

   public java.lang.Integer getDuracion()
   {
      return this.duracion;
   }

   public void setDuracion(java.lang.Integer duracion)
   {
      this.duracion = duracion;
   }

   public java.lang.String getCentro()
   {
      return this.centro;
   }

   public void setCentro(java.lang.String centro)
   {
      this.centro = centro;
   }

   public java.lang.String getPais()
   {
      return this.pais;
   }

   public void setPais(java.lang.String pais)
   {
      this.pais = pais;
   }

   public java.lang.String getCiudad()
   {
      return this.ciudad;
   }

   public void setCiudad(java.lang.String ciudad)
   {
      this.ciudad = ciudad;
   }

   public java.lang.String getLugar()
   {
      return this.lugar;
   }

   public void setLugar(java.lang.String lugar)
   {
      this.lugar = lugar;
   }

   public java.lang.String getModalidad()
   {
      return this.modalidad;
   }

   public void setModalidad(java.lang.String modalidad)
   {
      this.modalidad = modalidad;
   }

   public java.lang.String getInstructor()
   {
      return this.instructor;
   }

   public void setInstructor(java.lang.String instructor)
   {
      this.instructor = instructor;
   }

   public java.lang.String getFinanciamiento()
   {
      return this.financiamiento;
   }

   public void setFinanciamiento(java.lang.String financiamiento)
   {
      this.financiamiento = financiamiento;
   }

   public java.lang.Double getCosto()
   {
      return this.costo;
   }

   public void setCosto(java.lang.Double costo)
   {
      this.costo = costo;
   }

   public java.lang.String getJustificacion()
   {
      return this.justificacion;
   }

   public void setJustificacion(java.lang.String justificacion)
   {
      this.justificacion = justificacion;
   }

   public java.lang.String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(java.lang.String observaciones)
   {
      this.observaciones = observaciones;
   }

   public evento(
         java.lang.Long id,
         java.util.Date fecha,
         java.lang.String nombre,
         java.lang.String dependencia,
         java.lang.String descripcion,
         java.util.Date fechaInicio,
         java.util.Date fechaFin,
         java.lang.String horario,
         java.lang.Integer duracion,
         java.lang.String centro,
         java.lang.String pais,
         java.lang.String ciudad,
         java.lang.String lugar,
         java.lang.String modalidad,
         java.lang.String instructor,
         java.lang.String financiamiento,
         java.lang.Double costo,
         java.lang.String justificacion,
         java.lang.String observaciones,
         java.util.List<ucuenca.registrocapacitaciones.participante> participantes)
   {
      this.id = id;
      this.fecha = fecha;
      this.nombre = nombre;
      this.dependencia = dependencia;
      this.descripcion = descripcion;
      this.fechaInicio = fechaInicio;
      this.fechaFin = fechaFin;
      this.horario = horario;
      this.duracion = duracion;
      this.centro = centro;
      this.pais = pais;
      this.ciudad = ciudad;
      this.lugar = lugar;
      this.modalidad = modalidad;
      this.instructor = instructor;
      this.financiamiento = financiamiento;
      this.costo = costo;
      this.justificacion = justificacion;
      this.observaciones = observaciones;
      this.participantes = participantes;
   }

   public java.util.List<ucuenca.registrocapacitaciones.participante> getParticipantes()
   {
      return this.participantes;
   }

   public void setParticipantes(
         java.util.List<ucuenca.registrocapacitaciones.participante> participantes)
   {
      this.participantes = participantes;
   }

}